#!/bin/zsh

# Clear the current ansi sequence
cc() {
    printf -- '\033[0m'
}

# These are just the ansi sequences for telling if we're doing background, foreground, underline, etc.
ansiBG() {
    printf -- '\033[48;'
}

ansiFG() {
    printf -- '\033[1;38;'
}

ansiUL() {
    printf -- '\033[4;'
}

pathBGColor='2;0;0;0'
pathFGColor='5;82'
pathULColor='5;196'

fpathBGColor='5;1'
fpathFGColor='5;82'
fpathULColor='5;21'

# These are the actual ansi colors.
pathBG() {
    printf -- "${pathBGColor}m"
}

pathFG() {
    printf -- "${pathFGColor}m"
}

pathUL() {
    printf -- "58;${pathULColor}m"
}

fpathFG() {
    printf -- "${fpathFGColor}m"
}

fpathBG() {
    printf -- "${fpathBGColor}m"
}

fpathUL() {
    printf -- "58;${fpathULColor}m"
}

# Must have an ansi## followed by a (f)path##Color
pathBannerLeft() {
    ansiFG
    pathBG
    printf -- '\Ue0b6'
    cc
}
pathBannerBody() {
    ansiBG
    pathBG
    ansiFG
    pathFG
    ansiUL
    pathUL
    printf -- '<-::Exported $PATH::->'
    cc
}
pathBannerRight() {
    ansiFG
    pathBG
    echo '\Ue0b4'
    cc
}
pathList() {
    ansiFG
    pathFG
    print -l ${(s|:|)PATH}
    cc
}
fpathBannerLeft() {
    ansiFG
    fpathBG
    printf -- '\Ue0b6'
    cc
}
fpathBannerBody() {
    ansiBG
    fpathBG
    ansiFG
    fpathFG
    ansiUL
    fpathUL
    printf -- '<-::Exported $FPATH::->'
    cc
}
fpathBannerRight() {
    ansiFG
    fpathBG
    echo '\Ue0b4'
    cc
}
fpathList() {
    ansiFG
    fpathFG
    print -l ${(s|:|)FPATH}
    cc
}


pathBannerLeft
pathBannerBody
pathBannerRight
pathList

echo

fpathBannerLeft
fpathBannerBody
fpathBannerRight
fpathList


