#!/bin/zsh

# Clear the current ansi sequence
cc() {
    printf -- '\033[0m'
}

# These are just the ansi sequences for telling if we're doing background, foreground, underline, etc.
ansiBG() {
    printf -- '\033[48;'
}

ansiFG() {
    printf -- '\033[38;'
}

ansiUL() {
    printf -- '\033[4;'
}


# These are the actual ansi colors.
pathBGColor() {
    printf -- '2;0;0;0m'
}

pathFGColor() {
    printf -- '5;82m'
}

pathULColor() {
    printf -- '58;5;196m'
}

fpathFGColor() {
    printf -- '5;16m'
}

fpathBGColor() {
    printf -- '5;82m'
}

fpathULColor() {
    printf -- '58;5;21m'
}

# Must have an ansi## followed by a (f)path##Color



ansiFG
pathBGColor
printf -- '\Ue0b6'
cc
ansiBG
pathBGColor
ansiFG
pathFGColor
ansiUL
pathULColor
printf -- '<-::Exported $PATH::->'
cc
ansiFG
pathBGColor
printf -- '\Ue0b4'
ansiFG
pathFGColor
print -l ${(s|:|)PATH}
cc

ansiFG
fpathBGColor
printf -- '\Ue0b6'
cc
ansiBG
fpathBGColor
ansiFG
fpathFGColor
ansiUL
fpathULColor
printf -- '<-::Exported $FPATH::->'
cc
printf '\033[1;38;5;82m\Ue0b4'
print '\033[1;38;5;1m'
print -l ${(s|:|)FPATH}

