alias reload='exec zsh'
alias q='exit'
alias ppath='print -l $path'
alias cls=clear
alias ls='lsd --group-dirs first'
alias la='ls -A'
alias ll='ls -Al'
alias l='lsd --blocks date,name,size --date relative -tA'
alias cl='clear;la'
alias cll='clear;ll'
alias bk='cd ..'
alias ev='vim ~/.vimrc'
alias ep='vim ~/.zsh/aliases.zsh'
alias el='vim ~/.zsh/.zlogin'
alias rc='vim ~/.zsh/.zshrc'
alias cpdir="pwd | tr -d '\n' | pbcopy"
alias fl='fd -HI -d1'
# Dotfiles Version Control {{{1
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias cst='config status'
alias cpush='config push -u origin main'
alias cdl='config diff'
alias clcp='config log -p'
alias ccam='config commit -a -m'
alias clo='config log --oneline --all --decorate --graph'
# Homebrew {{{1
alias clean='brew cleanup --prune=all -s'
alias update='brew -v update'
alias upgrade='brew upgrade'
